version: '3'

networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.38.0.0/16

services:
  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 33380:80
    networks:
      my_network:
        ipv4_address: 172.38.0.2
    depends_on:
      - goCTF
      
  goCTF:
    image: ubuntu:20.04
    restart: always
    volumes:
      - ./goCTF/goCTF:/tmp/goCTF
    command: sh -c "/tmp/goCTF"
    networks:
      my_network:
        ipv4_address: 172.38.0.3
